--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/ShopUI
build-by-default: true
branches:
- main
projects:
  ShopUI:
    path: ""
  libs:
    - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
